server.port=8083
spring.application.name=travelgo-review-service

spring.datasource.url=jdbc:sqlite:data/reviews.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

packageservice.base-url=${GATEWAY_URL:http://localhost:8080}

springdoc.swagger-ui.path=/doc/swagger-ui.html
