spring.application.name=biblioteca
server.port=8081

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
spring.web.resources.add-mappings=true

# Configuración SQLite entregada por el profesor
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:data/travelgo.db
spring.datasource.username=
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Seguridad y errores (Sin uso por ahora)
logging.level.org.springframework.security=DEBUG
jwt.secret=Expedition33gano9premiosyesGOTYdel2026
jwt.expirationMinutes=120
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always